name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # Set this to the branch from which you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Install dependencies
      run: npm install

    - name: Deploy to Google App Engine
      run: gcloud app deploy app.yaml --quiet
