name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY_BASE64 }}
        export_default_credentials: true

    - name: Decode Google Cloud service account key
      run: echo ${{ secrets.GCP_SA_KEY_BASE64 }} | base64 --decode > ${{ github.workspace }}/gcp-key.json
      shell: bash

    - name: Activate Google Cloud service account
      run: gcloud auth activate-service-account --key-file="${{ github.workspace }}/gcp-key.json"

    - name: Install dependencies
      run: npm install

    - name: Deploy to Google App Engine
      run: gcloud app deploy app.yaml --quiet --verbosity=debug
